### ISSUE TITLE
Laplacian Filter

### ISSUE THREAD

**Issue by karol767** [karol767/image-contrast#1]
Detects edges well
Enhances corners
Can be computationally expensive

in this case, I'm considering whether which is better.

**Comment by aidatashark** [comment]
In my opinion, Bilateral Filter is more adapted well.
```
for file in files:
    print file
    img = cv2.imread(file,cv2.CV_LOAD_IMAGE_GRAYSCALE)
    gau =cv2.GaussianBlur(img, (3,3), 0)
    imean.append( gau.mean())
    imini.append(numpy.amin(gau))
    imaxi.append( numpy.amax(gau))
    filenamespl=file.split('\\')
    depth.append( int(filenamespl[-1][2:-4])*5 )
```

here, consider about benefits of  Reduces noise effectively.

**Comment by karol767** [comment]
@aidatashark
Thanks for your opinion.
I will consider again in version 2.0.
